// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo0u68AIaPN8HK8nvP4BhD9RlziJYQUQE',
    appId: '1:2233683249:web:3446df70222cc1bb537410',
    messagingSenderId: '2233683249',
    projectId: 'mynotes-flutter-project-83a14',
    authDomain: 'mynotes-flutter-project-83a14.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-83a14.appspot.com',
    measurementId: 'G-8NWB956QMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3QW1wfzETlOe98qt31NX2erhVcl70nhg',
    appId: '1:2233683249:android:120f657f55804406537410',
    messagingSenderId: '2233683249',
    projectId: 'mynotes-flutter-project-83a14',
    storageBucket: 'mynotes-flutter-project-83a14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH3QP2zkfkwtFZgQs_K_hhSHbKcXiI2oU',
    appId: '1:2233683249:ios:888760de1e8a3cbc537410',
    messagingSenderId: '2233683249',
    projectId: 'mynotes-flutter-project-83a14',
    storageBucket: 'mynotes-flutter-project-83a14.appspot.com',
    iosClientId: '2233683249-qv06134u6g556ptk7p5bqh5lnvf6qslc.apps.googleusercontent.com',
    iosBundleId: 'io.createnewprojectwithflutter.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH3QP2zkfkwtFZgQs_K_hhSHbKcXiI2oU',
    appId: '1:2233683249:ios:888760de1e8a3cbc537410',
    messagingSenderId: '2233683249',
    projectId: 'mynotes-flutter-project-83a14',
    storageBucket: 'mynotes-flutter-project-83a14.appspot.com',
    iosClientId: '2233683249-qv06134u6g556ptk7p5bqh5lnvf6qslc.apps.googleusercontent.com',
    iosBundleId: 'io.createnewprojectwithflutter.mynotes',
  );
}
